name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  AWS_REGION: us-east-1
  WORK_DIR: infrastructure
  WORK_DIR_FOR_TEST: tests
  TF_ENV: ${{ github.event.inputs.environment }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terrafrom
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init \
          -backend-config="backend/{{ env.TF_ENV }}.hcl" \
          -reconfigure
        working-directory: ${{ env.WORK_DIR }}

      # - name: Require file
      #   run: |
      #     if [ ! -f "secrets.env" ]; then
      #       echo "Missing required file"
      #       exit 1
      #     fi

      - name: Terraform Apply
        run: terraform apply \
          --auto-approve \
          -var-file="vars/${{ env.TF_ENV }}.tfvars"
          plans/${{ env.TF_ENV }}.tfplan
        working-directory: ${{ env.WORK_DIR }}

      - name: Setup Go environment
        uses: actions/setup-go@v5.5.0
      
      - name: Download Go Modules
        run: go mod download
        working-directory: ${{ env.WORK_DIR_FOR_TEST }}

      - name: Run Go Tests
        working-directory: ${{ env.WORK_DIR_FOR_TEST }}
        run: go test -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}