name: Check and Test

on:
  push:
    branches: [ "main", "feature", "week11task2" ]
  pull_request:
    branches: [ "main", "feature", "week11task2" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terrafrom
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure

      - name: tfsec action
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infrastructure

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4

      - name: Run tflint
        run: tflint -f compact
        working-directory: infrastructure

      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure

      - name: Terraform Format
        run: terraform fmt
        working-directory: infrastructure

      - name: Commit & Push formatted changes
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          message: "Auto format changes"

      - name: Terraform Plan
        run: terraform plan
        working-directory: infrastructure
